language: java

dist: focal

jdk:
  - openjdk14

sudo: false

env:

  global:
    - CODECOV_TOKEN="8c7ce971-e44b-4fc8-9333-87a695228568"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - kva.devops@gmail.com
    on_success: never
    on_failure: always